<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceSeeder extends Seeder {
    public function run(): void {
        DB::table('services')->insert([
            [
                'id'              => 1,
                'package_id'      => 1,
                'footage_size_id' => 1,
                'price'           => 119.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:04:28'),
                'updated_at'      => Carbon::parse('2025-07-16 04:04:28'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 2,
                'package_id'      => 1,
                'footage_size_id' => 1,
                'price'           => 139.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:44:42'),
                'updated_at'      => Carbon::parse('2025-07-16 04:44:42'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 3,
                'package_id'      => 1,
                'footage_size_id' => 1,
                'price'           => 159.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:45:06'),
                'updated_at'      => Carbon::parse('2025-07-16 04:45:06'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 4,
                'package_id'      => 1,
                'footage_size_id' => 2,
                'price'           => 129.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:45:46'),
                'updated_at'      => Carbon::parse('2025-07-16 04:45:46'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 5,
                'package_id'      => 1,
                'footage_size_id' => 2,
                'price'           => 149.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:46:08'),
                'updated_at'      => Carbon::parse('2025-07-16 04:46:08'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 6,
                'package_id'      => 1,
                'footage_size_id' => 2,
                'price'           => 169.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:46:27'),
                'updated_at'      => Carbon::parse('2025-07-16 04:46:27'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 7,
                'package_id'      => 1,
                'footage_size_id' => 3,
                'price'           => 159.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:46:58'),
                'updated_at'      => Carbon::parse('2025-07-16 04:46:58'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 8,
                'package_id'      => 1,
                'footage_size_id' => 3,
                'price'           => 179.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:47:17'),
                'updated_at'      => Carbon::parse('2025-07-16 04:47:17'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 9,
                'package_id'      => 1,
                'footage_size_id' => 3,
                'price'           => 199.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:47:31'),
                'updated_at'      => Carbon::parse('2025-07-16 04:47:31'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 10,
                'package_id'      => 1,
                'footage_size_id' => 4,
                'price'           => 189.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:47:55'),
                'updated_at'      => Carbon::parse('2025-07-16 04:47:55'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 11,
                'package_id'      => 1,
                'footage_size_id' => 4,
                'price'           => 209.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:48:18'),
                'updated_at'      => Carbon::parse('2025-07-16 04:48:18'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 12,
                'package_id'      => 1,
                'footage_size_id' => 4,
                'price'           => 229.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:48:43'),
                'updated_at'      => Carbon::parse('2025-07-16 04:48:43'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 13,
                'package_id'      => 2,
                'footage_size_id' => 1,
                'price'           => 169.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:50:20'),
                'updated_at'      => Carbon::parse('2025-07-16 04:50:20'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 14,
                'package_id'      => 2,
                'footage_size_id' => 1,
                'price'           => 189.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:50:46'),
                'updated_at'      => Carbon::parse('2025-07-16 04:50:46'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 15,
                'package_id'      => 2,
                'footage_size_id' => 1,
                'price'           => 209.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:51:13'),
                'updated_at'      => Carbon::parse('2025-07-16 04:51:13'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 16,
                'package_id'      => 2,
                'footage_size_id' => 2,
                'price'           => 179.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:51:43'),
                'updated_at'      => Carbon::parse('2025-07-16 04:51:43'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 17,
                'package_id'      => 2,
                'footage_size_id' => 2,
                'price'           => 199.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:52:04'),
                'updated_at'      => Carbon::parse('2025-07-16 04:52:04'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 18,
                'package_id'      => 2,
                'footage_size_id' => 2,
                'price'           => 219.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:52:31'),
                'updated_at'      => Carbon::parse('2025-07-16 04:52:31'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 19,
                'package_id'      => 2,
                'footage_size_id' => 3,
                'price'           => 209.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:53:46'),
                'updated_at'      => Carbon::parse('2025-07-16 04:53:46'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 20,
                'package_id'      => 2,
                'footage_size_id' => 3,
                'price'           => 229.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:54:16'),
                'updated_at'      => Carbon::parse('2025-07-16 04:54:16'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 21,
                'package_id'      => 2,
                'footage_size_id' => 3,
                'price'           => 249.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:54:52'),
                'updated_at'      => Carbon::parse('2025-07-16 04:54:52'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 22,
                'package_id'      => 2,
                'footage_size_id' => 4,
                'price'           => 259.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:55:59'),
                'updated_at'      => Carbon::parse('2025-07-16 04:55:59'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 23,
                'package_id'      => 2,
                'footage_size_id' => 4,
                'price'           => 259.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:56:43'),
                'updated_at'      => Carbon::parse('2025-07-16 04:56:43'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 24,
                'package_id'      => 2,
                'footage_size_id' => 4,
                'price'           => 279.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:57:00'),
                'updated_at'      => Carbon::parse('2025-07-16 04:57:00'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 25,
                'package_id'      => 3,
                'footage_size_id' => 1,
                'price'           => 229.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:57:42'),
                'updated_at'      => Carbon::parse('2025-07-16 04:57:42'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 26,
                'package_id'      => 3,
                'footage_size_id' => 1,
                'price'           => 249.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:58:49'),
                'updated_at'      => Carbon::parse('2025-07-16 04:58:49'),
                'deleted_at'      => null,
            ],
            [
                'id'              => 27,
                'package_id'      => 3,
                'footage_size_id' => 1,
                'price'           => 269.00,
                'status'          => 'active',
                'created_at'      => Carbon::parse('2025-07-16 04:59:17'),
                'updated_at'      => Carbon::parse('2025-07-16 05:01:19'),
                'deleted_at'      => null,
            ],
        ]);
    }
}
