<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceItemsPivotSeeder extends Seeder {
    public function run(): void {
        DB::table('service_items_pivot')->insert([
            [
                'id'              => 1,
                'service_id'      => 1,
                'service_item_id' => 1,
                'quantity'        => 15,
                'created_at'      => Carbon::parse('2025-07-16 04:04:28'),
                'updated_at'      => Carbon::parse('2025-07-16 04:04:28'),
            ],
            [
                'id'              => 2,
                'service_id'      => 2,
                'service_item_id' => 1,
                'quantity'        => 20,
                'created_at'      => Carbon::parse('2025-07-16 04:44:42'),
                'updated_at'      => Carbon::parse('2025-07-16 04:44:42'),
            ],
            [
                'id'              => 3,
                'service_id'      => 3,
                'service_item_id' => 1,
                'quantity'        => 30,
                'created_at'      => Carbon::parse('2025-07-16 04:45:06'),
                'updated_at'      => Carbon::parse('2025-07-16 04:45:06'),
            ],
            [
                'id'              => 4,
                'service_id'      => 4,
                'service_item_id' => 1,
                'quantity'        => 15,
                'created_at'      => Carbon::parse('2025-07-16 04:45:46'),
                'updated_at'      => Carbon::parse('2025-07-16 04:45:46'),
            ],
            [
                'id'              => 5,
                'service_id'      => 5,
                'service_item_id' => 1,
                'quantity'        => 20,
                'created_at'      => Carbon::parse('2025-07-16 04:46:08'),
                'updated_at'      => Carbon::parse('2025-07-16 04:46:08'),
            ],
            [
                'id'              => 6,
                'service_id'      => 6,
                'service_item_id' => 1,
                'quantity'        => 30,
                'created_at'      => Carbon::parse('2025-07-16 04:46:27'),
                'updated_at'      => Carbon::parse('2025-07-16 04:46:27'),
            ],
            [
                'id'              => 7,
                'service_id'      => 7,
                'service_item_id' => 1,
                'quantity'        => 20,
                'created_at'      => Carbon::parse('2025-07-16 04:46:58'),
                'updated_at'      => Carbon::parse('2025-07-16 04:46:58'),
            ],
            [
                'id'              => 8,
                'service_id'      => 8,
                'service_item_id' => 1,
                'quantity'        => 25,
                'created_at'      => Carbon::parse('2025-07-16 04:47:17'),
                'updated_at'      => Carbon::parse('2025-07-16 04:47:17'),
            ],
            [
                'id'              => 9,
                'service_id'      => 9,
                'service_item_id' => 1,
                'quantity'        => 35,
                'created_at'      => Carbon::parse('2025-07-16 04:47:31'),
                'updated_at'      => Carbon::parse('2025-07-16 04:47:31'),
            ],
            [
                'id'              => 10,
                'service_id'      => 10,
                'service_item_id' => 1,
                'quantity'        => 25,
                'created_at'      => Carbon::parse('2025-07-16 04:47:55'),
                'updated_at'      => Carbon::parse('2025-07-16 04:47:55'),
            ],
            [
                'id'              => 11,
                'service_id'      => 11,
                'service_item_id' => 1,
                'quantity'        => 30,
                'created_at'      => Carbon::parse('2025-07-16 04:48:18'),
                'updated_at'      => Carbon::parse('2025-07-16 04:48:18'),
            ],
            [
                'id'              => 12,
                'service_id'      => 12,
                'service_item_id' => 1,
                'quantity'        => 40,
                'created_at'      => Carbon::parse('2025-07-16 04:48:43'),
                'updated_at'      => Carbon::parse('2025-07-16 04:48:43'),
            ],
            [
                'id'              => 13,
                'service_id'      => 13,
                'service_item_id' => 1,
                'quantity'        => 15,
                'created_at'      => Carbon::parse('2025-07-16 04:50:20'),
                'updated_at'      => Carbon::parse('2025-07-16 04:50:20'),
            ],
            [
                'id'              => 14,
                'service_id'      => 13,
                'service_item_id' => 2,
                'quantity'        => 5,
                'created_at'      => Carbon::parse('2025-07-16 04:50:20'),
                'updated_at'      => Carbon::parse('2025-07-16 04:50:20'),
            ],
            [
                'id'              => 15,
                'service_id'      => 14,
                'service_item_id' => 1,
                'quantity'        => 20,
                'created_at'      => Carbon::parse('2025-07-16 04:50:46'),
                'updated_at'      => Carbon::parse('2025-07-16 04:50:46'),
            ],
            [
                'id'              => 16,
                'service_id'      => 14,
                'service_item_id' => 2,
                'quantity'        => 5,
                'created_at'      => Carbon::parse('2025-07-16 04:50:46'),
                'updated_at'      => Carbon::parse('2025-07-16 04:50:46'),
            ],
            [
                'id'              => 17,
                'service_id'      => 15,
                'service_item_id' => 1,
                'quantity'        => 30,
                'created_at'      => Carbon::parse('2025-07-16 04:51:13'),
                'updated_at'      => Carbon::parse('2025-07-16 04:51:13'),
            ],
            [
                'id'              => 18,
                'service_id'      => 15,
                'service_item_id' => 2,
                'quantity'        => 5,
                'created_at'      => Carbon::parse('2025-07-16 04:51:13'),
                'updated_at'      => Carbon::parse('2025-07-16 04:51:13'),
            ],
            [
                'id'              => 19,
                'service_id'      => 16,
                'service_item_id' => 1,
                'quantity'        => 15,
                'created_at'      => Carbon::parse('2025-07-16 04:51:43'),
                'updated_at'      => Carbon::parse('2025-07-16 04:51:43'),
            ],
            [
                'id'              => 20,
                'service_id'      => 16,
                'service_item_id' => 2,
                'quantity'        => 5,
                'created_at'      => Carbon::parse('2025-07-16 04:51:43'),
                'updated_at'      => Carbon::parse('2025-07-16 04:51:43'),
            ],
            [
                'id'              => 21,
                'service_id'      => 17,
                'service_item_id' => 1,
                'quantity'        => 20,
                'created_at'      => Carbon::parse('2025-07-16 04:52:04'),
                'updated_at'      => Carbon::parse('2025-07-16 04:52:04'),
            ],
            [
                'id'              => 22,
                'service_id'      => 17,
                'service_item_id' => 2,
                'quantity'        => 5,
                'created_at'      => Carbon::parse('2025-07-16 04:52:04'),
                'updated_at'      => Carbon::parse('2025-07-16 04:52:04'),
            ],
            [
                'id'              => 23,
                'service_id'      => 18,
                'service_item_id' => 1,
                'quantity'        => 30,
                'created_at'      => Carbon::parse('2025-07-16 04:52:31'),
                'updated_at'      => Carbon::parse('2025-07-16 04:52:31'),
            ],
            [
                'id'              => 24,
                'service_id'      => 18,
                'service_item_id' => 2,
                'quantity'        => 5,
                'created_at'      => Carbon::parse('2025-07-16 04:52:31'),
                'updated_at'      => Carbon::parse('2025-07-16 04:52:31'),
            ],
            [
                'id'              => 25,
                'service_id'      => 19,
                'service_item_id' => 1,
                'quantity'        => 20,
                'created_at'      => Carbon::parse('2025-07-16 04:53:46'),
                'updated_at'      => Carbon::parse('2025-07-16 04:53:46'),
            ],
            [
                'id'              => 26,
                'service_id'      => 19,
                'service_item_id' => 2,
                'quantity'        => 5,
                'created_at'      => Carbon::parse('2025-07-16 04:53:46'),
                'updated_at'      => Carbon::parse('2025-07-16 04:53:46'),
            ],
            [
                'id'              => 27,
                'service_id'      => 20,
                'service_item_id' => 1,
                'quantity'        => 25,
                'created_at'      => Carbon::parse('2025-07-16 04:54:16'),
                'updated_at'      => Carbon::parse('2025-07-16 04:54:16'),
            ],
            [
                'id'              => 28,
                'service_id'      => 20,
                'service_item_id' => 2,
                'quantity'        => 5,
                'created_at'      => Carbon::parse('2025-07-16 04:54:16'),
                'updated_at'      => Carbon::parse('2025-07-16 04:54:16'),
            ],
            [
                'id'              => 29,
                'service_id'      => 21,
                'service_item_id' => 1,
                'quantity'        => 35,
                'created_at'      => Carbon::parse('2025-07-16 04:54:52'),
                'updated_at'      => Carbon::parse('2025-07-16 04:54:52'),
            ],
            [
                'id'              => 30,
                'service_id'      => 21,
                'service_item_id' => 2,
                'quantity'        => 5,
                'created_at'      => Carbon::parse('2025-07-16 04:54:52'),
                'updated_at'      => Carbon::parse('2025-07-16 04:54:52'),
            ],
            [
                'id'              => 31,
                'service_id'      => 22,
                'service_item_id' => 1,
                'quantity'        => 25,
                'created_at'      => Carbon::parse('2025-07-16 04:55:59'),
                'updated_at'      => Carbon::parse('2025-07-16 04:55:59'),
            ],
            [
                'id'              => 32,
                'service_id'      => 22,
                'service_item_id' => 2,
                'quantity'        => 5,
                'created_at'      => Carbon::parse('2025-07-16 04:55:59'),
                'updated_at'      => Carbon::parse('2025-07-16 04:55:59'),
            ],
            [
                'id'              => 33,
                'service_id'      => 23,
                'service_item_id' => 1,
                'quantity'        => 30,
                'created_at'      => Carbon::parse('2025-07-16 04:56:43'),
                'updated_at'      => Carbon::parse('2025-07-16 04:56:43'),
            ],
            [
                'id'              => 34,
                'service_id'      => 23,
                'service_item_id' => 2,
                'quantity'        => 5,
                'created_at'      => Carbon::parse('2025-07-16 04:56:43'),
                'updated_at'      => Carbon::parse('2025-07-16 04:56:43'),
            ],
            [
                'id'              => 35,
                'service_id'      => 24,
                'service_item_id' => 1,
                'quantity'        => 40,
                'created_at'      => Carbon::parse('2025-07-16 04:57:00'),
                'updated_at'      => Carbon::parse('2025-07-16 04:57:00'),
            ],
            [
                'id'              => 36,
                'service_id'      => 24,
                'service_item_id' => 2,
                'quantity'        => 5,
                'created_at'      => Carbon::parse('2025-07-16 04:57:00'),
                'updated_at'      => Carbon::parse('2025-07-16 04:57:00'),
            ],
            [
                'id'              => 37,
                'service_id'      => 25,
                'service_item_id' => 1,
                'quantity'        => 15,
                'created_at'      => Carbon::parse('2025-07-16 04:57:42'),
                'updated_at'      => Carbon::parse('2025-07-16 04:57:42'),
            ],
            [
                'id'              => 38,
                'service_id'      => 25,
                'service_item_id' => 2,
                'quantity'        => 5,
                'created_at'      => Carbon::parse('2025-07-16 04:57:42'),
                'updated_at'      => Carbon::parse('2025-07-16 04:57:42'),
            ],
            [
                'id'              => 39,
                'service_id'      => 25,
                'service_item_id' => 3,
                'quantity'        => 1,
                'created_at'      => Carbon::parse('2025-07-16 04:57:42'),
                'updated_at'      => Carbon::parse('2025-07-16 04:57:42'),
            ],
            [
                'id'              => 40,
                'service_id'      => 26,
                'service_item_id' => 1,
                'quantity'        => 20,
                'created_at'      => Carbon::parse('2025-07-16 04:58:49'),
                'updated_at'      => Carbon::parse('2025-07-16 04:58:49'),
            ],
            [
                'id'              => 41,
                'service_id'      => 26,
                'service_item_id' => 2,
                'quantity'        => 5,
                'created_at'      => Carbon::parse('2025-07-16 04:58:49'),
                'updated_at'      => Carbon::parse('2025-07-16 04:58:49'),
            ],
            [
                'id'              => 42,
                'service_id'      => 26,
                'service_item_id' => 3,
                'quantity'        => 1,
                'created_at'      => Carbon::parse('2025-07-16 04:58:49'),
                'updated_at'      => Carbon::parse('2025-07-16 04:58:49'),
            ],
            [
                'id'              => 46,
                'service_id'      => 27,
                'service_item_id' => 1,
                'quantity'        => 30,
                'created_at'      => Carbon::parse('2025-07-16 05:01:19'),
                'updated_at'      => Carbon::parse('2025-07-16 05:01:19'),
            ],
            [
                'id'              => 47,
                'service_id'      => 27,
                'service_item_id' => 2,
                'quantity'        => 5,
                'created_at'      => Carbon::parse('2025-07-16 05:01:19'),
                'updated_at'      => Carbon::parse('2025-07-16 05:01:19'),
            ],
            [
                'id'              => 48,
                'service_id'      => 27,
                'service_item_id' => 3,
                'quantity'        => 1,
                'created_at'      => Carbon::parse('2025-07-16 05:01:19'),
                'updated_at'      => Carbon::parse('2025-07-16 05:01:19'),
            ],
        ]);
    }
}
